-- ═══════════════════════════════════════════════════════════════════════════
-- kanyoai — Complete Supabase Setup
-- Paste into: Supabase Dashboard → SQL Editor → New query → Run
-- ═══════════════════════════════════════════════════════════════════════════

-- ── 1. Extensions ────────────────────────────────────────────────────────────

create extension if not exists "uuid-ossp";

-- ── 2. profiles ──────────────────────────────────────────────────────────────
-- One row per auth user, auto-created by trigger below.

create table if not exists public.profiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  email       text,
  full_name   text,
  avatar_url  text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- Auto-create a profile row on every new sign-up
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer
set search_path = public as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', ''),
    coalesce(new.raw_user_meta_data->>'avatar_url', '')
  )
  on conflict (id) do update
    set email      = excluded.email,
        updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ── 3. ai_projects ───────────────────────────────────────────────────────────
-- Stores every website generated by the AI builder.

create table if not exists public.ai_projects (
  id            uuid primary key default uuid_generate_v4(),
  user_id       uuid not null references auth.users(id) on delete cascade,
  title         text not null default 'Untitled project',
  kind          text not null default 'portfolio',
  model         text,
  brief         jsonb,
  files         jsonb,
  style         jsonb,
  thumbnail_url text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- Fast lookup: user's projects sorted by recency
create index if not exists ai_projects_user_updated
  on public.ai_projects(user_id, updated_at desc);

-- Keep updated_at current on every edit
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists ai_projects_set_updated_at on public.ai_projects;
create trigger ai_projects_set_updated_at
  before update on public.ai_projects
  for each row execute procedure public.set_updated_at();

-- ── 4. RLS — profiles ────────────────────────────────────────────────────────

alter table public.profiles enable row level security;

drop policy if exists "profiles: owner read"   on public.profiles;
drop policy if exists "profiles: owner update" on public.profiles;

create policy "profiles: owner read"
  on public.profiles for select
  using (auth.uid() = id);

create policy "profiles: owner update"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- ── 5. RLS — ai_projects ─────────────────────────────────────────────────────

alter table public.ai_projects enable row level security;

drop policy if exists "ai_projects: owner read"   on public.ai_projects;
drop policy if exists "ai_projects: owner insert" on public.ai_projects;
drop policy if exists "ai_projects: owner update" on public.ai_projects;
drop policy if exists "ai_projects: owner delete" on public.ai_projects;

create policy "ai_projects: owner read"
  on public.ai_projects for select
  using (auth.uid() = user_id);

create policy "ai_projects: owner insert"
  on public.ai_projects for insert
  with check (auth.uid() = user_id);

create policy "ai_projects: owner update"
  on public.ai_projects for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "ai_projects: owner delete"
  on public.ai_projects for delete
  using (auth.uid() = user_id);

-- ── 6. Storage bucket: user-images ───────────────────────────────────────────
-- Public bucket so image URLs work in exported code without auth tokens.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'user-images',
  'user-images',
  true,
  10485760,   -- 10 MB per file
  array['image/png','image/jpeg','image/webp','image/gif']
)
on conflict (id) do update
  set public           = true,
      file_size_limit  = 10485760,
      allowed_mime_types = array['image/png','image/jpeg','image/webp','image/gif'];

-- Anyone can read (public URLs work in exported HTML)
drop policy if exists "user-images: public read"  on storage.objects;
create policy "user-images: public read"
  on storage.objects for select
  using (bucket_id = 'user-images');

-- Signed-in users can only upload to their own <user_id>/ folder
drop policy if exists "user-images: owner insert" on storage.objects;
create policy "user-images: owner insert"
  on storage.objects for insert
  with check (
    bucket_id = 'user-images'
    and auth.uid() is not null
    and (storage.foldername(name))[1] = auth.uid()::text
  );

-- Users can update/delete only their own files
drop policy if exists "user-images: owner update" on storage.objects;
create policy "user-images: owner update"
  on storage.objects for update
  using (bucket_id = 'user-images' and auth.uid()::text = (storage.foldername(name))[1]);

drop policy if exists "user-images: owner delete" on storage.objects;
create policy "user-images: owner delete"
  on storage.objects for delete
  using (bucket_id = 'user-images' and auth.uid()::text = (storage.foldername(name))[1]);
