-- ═══════════════════════════════════════════════════════════════════════════
--  kanyoai — complete Supabase setup
--  Paste entire file into: Dashboard → SQL Editor → New query → Run
--  Safe to run multiple times (all statements are idempotent).
-- ═══════════════════════════════════════════════════════════════════════════


-- ── 1. Extensions ────────────────────────────────────────────────────────────

create extension if not exists "uuid-ossp";


-- ── 2. Profiles table ────────────────────────────────────────────────────────
-- One row per user. Auto-created by the trigger below.
-- Works for email/password AND OAuth (Google, GitHub) —
-- raw_user_meta_data carries full_name / avatar_url from the provider.

create table if not exists public.profiles (
  id          uuid        primary key references auth.users(id) on delete cascade,
  email       text,
  full_name   text,
  avatar_url  text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);


-- ── 3. Trigger: auto-create profile on every new user ────────────────────────
-- Fires on INSERT into auth.users (email signup + every OAuth provider).

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (
    new.id,
    new.email,
    coalesce(
      new.raw_user_meta_data->>'full_name',
      new.raw_user_meta_data->>'name',
      ''
    ),
    coalesce(
      new.raw_user_meta_data->>'avatar_url',
      new.raw_user_meta_data->>'picture',
      ''
    )
  )
  on conflict (id) do update set
    email      = excluded.email,
    full_name  = coalesce(nullif(excluded.full_name,  ''), profiles.full_name),
    avatar_url = coalesce(nullif(excluded.avatar_url, ''), profiles.avatar_url),
    updated_at = now();
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();


-- ── 4. AI projects table ─────────────────────────────────────────────────────
-- Stores every website generated by the AI Generator.

create table if not exists public.ai_projects (
  id            uuid        primary key default uuid_generate_v4(),
  user_id       uuid        not null references auth.users(id) on delete cascade,
  title         text        not null default 'Untitled project',
  kind          text        not null default 'portfolio',
  model         text,
  brief         jsonb,
  files         jsonb,
  style         jsonb,
  thumbnail_url text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);


-- ── 5. Trigger: keep updated_at current ──────────────────────────────────────

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists ai_projects_updated_at on public.ai_projects;
create trigger ai_projects_updated_at
  before update on public.ai_projects
  for each row execute function public.set_updated_at();


-- ── 6. Index ─────────────────────────────────────────────────────────────────
-- Speeds up "load my projects ordered by last updated" on the dashboard.

create index if not exists ai_projects_user_updated
  on public.ai_projects (user_id, updated_at desc);


-- ── 7. Row-Level Security ────────────────────────────────────────────────────

alter table public.profiles    enable row level security;
alter table public.ai_projects enable row level security;

-- profiles: each user reads and updates only their own row
drop policy if exists "profiles_select" on public.profiles;
create policy "profiles_select" on public.profiles
  for select using (auth.uid() = id);

drop policy if exists "profiles_update" on public.profiles;
create policy "profiles_update" on public.profiles
  for update using (auth.uid() = id)
  with check (auth.uid() = id);

-- ai_projects: full CRUD on own rows only
drop policy if exists "projects_select" on public.ai_projects;
create policy "projects_select" on public.ai_projects
  for select using (auth.uid() = user_id);

drop policy if exists "projects_insert" on public.ai_projects;
create policy "projects_insert" on public.ai_projects
  for insert with check (auth.uid() = user_id);

drop policy if exists "projects_update" on public.ai_projects;
create policy "projects_update" on public.ai_projects
  for update using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

drop policy if exists "projects_delete" on public.ai_projects;
create policy "projects_delete" on public.ai_projects
  for delete using (auth.uid() = user_id);

-- also drop old-style policy names from previous versions
drop policy if exists "profiles: owner read"    on public.profiles;
drop policy if exists "profiles: owner update"  on public.profiles;
drop policy if exists "ai_projects: owner read"   on public.ai_projects;
drop policy if exists "ai_projects: owner insert" on public.ai_projects;
drop policy if exists "ai_projects: owner update" on public.ai_projects;
drop policy if exists "ai_projects: owner delete" on public.ai_projects;


-- ── 8. Storage bucket ────────────────────────────────────────────────────────
-- Public bucket — images served directly in exported <img> tags without auth.
-- 10 MB max per file. Images only.

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'user-images',
  'user-images',
  true,
  10485760,
  array['image/png', 'image/jpeg', 'image/webp', 'image/gif']
)
on conflict (id) do update set
  public             = true,
  file_size_limit    = 10485760,
  allowed_mime_types = array['image/png', 'image/jpeg', 'image/webp', 'image/gif'];


-- ── 9. Storage RLS policies ───────────────────────────────────────────────────
-- Public read  — anyone can load images (needed for exported site <img> tags).
-- Write/delete — owner only (files must be under <user_id>/ folder).

drop policy if exists "user-images: public read"  on storage.objects;
drop policy if exists "user-images: owner insert" on storage.objects;
drop policy if exists "user-images: owner update" on storage.objects;
drop policy if exists "user-images: owner delete" on storage.objects;
drop policy if exists "images_public_read"        on storage.objects;
drop policy if exists "images_owner_insert"       on storage.objects;
drop policy if exists "images_owner_update"       on storage.objects;
drop policy if exists "images_owner_delete"       on storage.objects;

create policy "images_public_read" on storage.objects
  for select using (bucket_id = 'user-images');

create policy "images_owner_insert" on storage.objects
  for insert with check (
    bucket_id = 'user-images'
    and auth.uid() is not null
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "images_owner_update" on storage.objects
  for update using (
    bucket_id = 'user-images'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

create policy "images_owner_delete" on storage.objects
  for delete using (
    bucket_id = 'user-images'
    and (storage.foldername(name))[1] = auth.uid()::text
  );


-- ═══════════════════════════════════════════════════════════════════════════
--  AFTER RUNNING THIS SQL — complete these steps in the Supabase dashboard:
--
--  GOOGLE OAUTH
--    Authentication → Providers → Google → Enable
--    Paste Client ID + Secret  (from console.cloud.google.com)
--    Authorized redirect URI:  https://YOUR_PROJECT.supabase.co/auth/v1/callback
--
--  GITHUB OAUTH
--    Authentication → Providers → GitHub → Enable
--    Paste Client ID + Secret  (from github.com/settings/developers)
--    Callback URL:             https://YOUR_PROJECT.supabase.co/auth/v1/callback
--
--  REDIRECT ALLOW-LIST
--    Authentication → URL Configuration → Redirect URLs → Add:
--      https://yourdomain.com/dashboard
--      http://localhost:5173/dashboard     ← local dev
--
--  VERCEL ENV VARS  (Project → Settings → Environment Variables)
--    VITE_SUPABASE_URL              → your project URL
--    VITE_SUPABASE_PUBLISHABLE_KEY  → anon/public key
--    SUPABASE_URL                   → same project URL (server-side)
--    SUPABASE_SERVICE_ROLE_KEY      → service role key (keep secret)
--    OPENAI_API_KEY                 → your OpenAI key
-- ═══════════════════════════════════════════════════════════════════════════
